version: "3.8"

services:
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - movie4u:/data/db
      - /usr/src/app/node_modules
  api:
    build: ./
    ports:
      - 3333:3333
    environment:
      DB_URL: mongodb://db/movie4u
      movie4u_jwtPrivateKey: MySecureKey
    depends_on:
      - db
volumes:
  movie4u:
